"""Initial schema setup

Revision ID: 102711083279
Revises: 
Create Date: 2026-10-08 10:26:55.444833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102711083279'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('merchant_confidence', sa.Float(), nullable=True),
    sa.Column('purchase_date_confidence', sa.Float(), nullable=True),
    sa.Column('currency_confidence', sa.Float(), nullable=True),
    sa.Column('total_confidence', sa.Float(), nullable=True),
    sa.Column('line_items', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('image_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
